name: Nightly experiment
on:
  push:
    paths:
      - '.github/workflows/nightly-experiment.yml'



jobs:
  wildbook-ia:
    name: Building mmulich/wildbook-ia:nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/mmulich/wildbook-ia:nightly

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  wbia-base-images:
    name: Building mmulich/{wbia-base,wbia-dependencies,wbia-provision,wbia}:nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push wbia-base:nightly
        id: wbia_base_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./devops/base/Dockerfile
          push: true
          tags: ghcr.io/mmulich/wbia-base:nightly

      - name: Build and push wbia-dependencies:nightly
        id: wbia_dependencies_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./devops/dependencies/Dockerfile
          push: true
          tags: ghcr.io/mmulich/wbia-dependencies:nightly

      - name: Build and push wbia-provision:nightly
        id: wbia_provision_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./devops/provision/Dockerfile
          push: true
          tags: ghcr.io/mmulich/wbia-provision:nightly
          build-args: |
            VCS_REF=fix-nightly
            VCS_URL=https://github.com/mmulich/wildbook-ia

      - name: Build and push wbia:nightly
        id: wbia_build
        uses: docker/build-push-action@v2
        with:
          context: ./devops/
          file: ./devops/Dockerfile
          push: true
          tags: ghcr.io/mmulich/wbia:nightly

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
