name: Nightly experiment
on:
  push:
    paths:
      - '.github/workflows/nightly-experiment.yml'



jobs:
  wildbook-ia:
    name: Building mmulich/wildbook-ia:nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/mmulich/wildbook-ia:nightly

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  wbia-base-image:
    name: Building mmulich/{wbia-base,wbia-dependencies,wbia-provision,wbia}:nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        env:
          cache-name: cache-base
        with:
          path: /tmp/.buildx-cache
          # Cache invalidated when any file in the 'devops' directory changes
          key: ${{ runner.os }}-buildx-${{ env.cache-name }}-${{ hashFiles('devops/**') }}
          restore-keys: ${{ runner.os }}-buildx-${{ env.cache-name }}-${{ hashFiles('devops/**') }}
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push wbia-base:nightly
        id: wbia_base_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./devops/base/Dockerfile
          push: true
          tags: ghcr.io/mmulich/wbia-base:nightly
          cache-from: type=local,src=/tmp/.buildx-cache/base
          cache-to: type=local,dest=/tmp/.buildx-cache/base
      - name: Image digest
        run: echo ${{ steps.wbia_base_build.outputs.digest }}


  wbia-dependencies-image:
    name: Building mmulich/wbia-dependencies:nightly
    runs-on: ubuntu-latest
    needs: [ wbia-base-image ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies
        with:
          path: /tmp/.buildx-cache
          # Cache invalidated when any file in the 'devops' directory changes
          key: ${{ runner.os }}-buildx-${{ env.cache-name }}-${{ hashFiles('devops/**') }}
          restore-keys: ${{ runner.os }}-buildx-${{ env.cache-name }}-${{ hashFiles('devops/**') }}
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push wbia-dependencies:nightly
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./devops/dependencies/Dockerfile
          push: true
          tags: ghcr.io/mmulich/wbia-dependencies:nightly
          cache-from: type=local,src=/tmp/.buildx-cache/dependencies
          cache-to: type=local,dest=/tmp/.buildx-cache/dependencies
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


  wbia-provision-image:
    name: Building mmulich/wbia-provision:nightly
    runs-on: ubuntu-latest
    needs: [ wbia-dependencies-image ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        env:
          cache-name: cache-provision
        with:
          path: /tmp/.buildx-cache
          # Cache invalidated when any file in the 'devops' directory changes
          key: ${{ runner.os }}-buildx-${{ env.cache-name }}-${{ hashFiles('devops/**') }}
          restore-keys: ${{ runner.os }}-buildx-${{ env.cache-name }}-${{ hashFiles('devops/**') }}
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push wbia-provision:nightly
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./devops/provision/Dockerfile
          push: true
          tags: ghcr.io/mmulich/wbia-provision:nightly
          build-args: |
            VCS_REF=fix-nightly
            VCS_URL=https://github.com/mmulich/wildbook-ia
          cache-from: type=local,src=/tmp/.buildx-cache/provision
          cache-to: type=local,dest=/tmp/.buildx-cache/provision
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


  wbia-image:
    name: Building mmulich/wbia:nightly
    runs-on: ubuntu-latest
    needs: [ wbia-provision-image ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        env:
          cache-name: cache-provision
        with:
          path: /tmp/.buildx-cache
          # Cache invalidated when any file in the 'devops' directory changes
          key: ${{ runner.os }}-buildx-${{ env.cache-name }}-${{ hashFiles('devops/**') }}
          restore-keys: ${{ runner.os }}-buildx-${{ env.cache-name }}-${{ hashFiles('devops/**') }}
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push wbia:nightly
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./devops/
          file: ./devops/Dockerfile
          push: true
          tags: ghcr.io/mmulich/wbia:nightly
          cache-from: type=local,src=/tmp/.buildx-cache/wbia
          cache-to: type=local,dest=/tmp/.buildx-cache/wbia
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
